spring.application.name=Zluket
spring.shell.interactive.enabled=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

spring.session.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=update

spring.web.resources.static-locations=classpath:/public/

spring.output.ansi.enabled=always
logging.file.name=logs/zluket.log
logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.max-history=20

spring.datasource.hikari.isolate-internal-queries=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.register-mbeans=true

zluket.api.content.max_length=100000
